[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
version = "1.38.0"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[env]
NODE_ENV = "production"
