[build]
builder = "nixpacks"
# Simple build command without cache clearing
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
# Don't disable cache - might help with build stability
# NIXPACKS_NO_CACHE = "1"
NEXT_TELEMETRY_DISABLED = "1"
# Increase memory for build
NODE_OPTIONS = "--max-old-space-size=4096"
