[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules/.cache .next/cache && npm ci && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_NO_CACHE = "1"
