#!/usr/bin/env npx tsx

import { config } from 'dotenv';
import { resolve } from 'path';

config({ path: resolve(process.cwd(), '.env.local') });

async function checkWorkflow() {
  const admin = await import('firebase-admin');

  if (!admin.default.apps.length) {
    const serviceAccount = {
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    };

    admin.default.initializeApp({
      credential: admin.default.credential.cert(serviceAccount as any),
    });
  }

  const db = admin.default.firestore();

  // Get the workflow by ID (from test output)
  const workflowId = 'property_15sec_es_1763005997564_zm22i';
  const doc = await db.collection('property_videos').doc(workflowId).get();

  if (!doc.exists) {
    console.log('❌ Workflow not found');
    return;
  }

  const data = doc.data()!;

  console.log('\n✅ Spanish Workflow Details:');
  console.log('   Workflow ID:', doc.id);
  console.log('   Language:', data.language);
  console.log('   Property:', data.propertyAddress);
  console.log('   Status:', data.status);
  console.log('   Video Title:', data.videoTitle);
  console.log('\n📝 Script (Spanish):');
  console.log(data.script);
  console.log('\n🎬 HeyGen:');
  console.log('   Status:', data.heygenStatus || 'pending');
  console.log('   Video ID:', data.heygenVideoId || 'waiting...');
  
  console.log('\n✅ Workflow Pipeline:');
  console.log('   1. ✅ Spanish script generated by OpenAI');
  console.log('   2. ⏳ HeyGen processing avatar video...');
  console.log('   3. ⏳ Submagic will add Spanish captions');
  console.log('   4. ⏳ Video will be posted to GetLate queue');
}

checkWorkflow().catch(console.error);
