import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

// Simulate the exact flow Juan goes through
async function debugJuanLogin() {
  const phone = '9016796871';
  const baseUrl = 'http://localhost:3000'; // Change to production URL if testing production
  
  console.log('=== SIMULATING JUAN\'S LOGIN FLOW ===\n');
  console.log('Phone input:', phone);
  
  // Step 1: Normalize phone (client-side)
  function normalizePhone(phone: string): string {
    const cleaned = phone.replace(/\D/g, '');
    const last10 = cleaned.slice(-10);
    if (last10.length !== 10) return phone;
    return `+1${last10}`;
  }
  
  const normalizedPhone = normalizePhone(phone);
  console.log('Normalized phone:', normalizedPhone);
  
  // Step 2: Check if user exists (after OTP verification)
  console.log('\n=== CALLING /api/auth/check-phone ===');
  
  try {
    const checkResponse = await fetch(`${baseUrl}/api/auth/check-phone`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ phone: normalizedPhone })
    });
    
    console.log('Response status:', checkResponse.status);
    const checkData = await checkResponse.json();
    console.log('Response data:', JSON.stringify(checkData, null, 2));
    
    if (checkData.exists) {
      console.log('\n✅ User exists!');
      console.log('  - Should proceed to login');
      console.log('  - Role:', checkData.role);
      console.log('  - UserId:', checkData.userId);
      console.log('  - IsInvestor:', checkData.isInvestor);
    } else {
      console.log('\n❌ User not found!');
      console.log('  - Would redirect to /auth/setup');
      console.log('  - This creates a NEW account');
    }
  } catch (error) {
    console.error('Error calling check-phone:', error);
  }
  
  // Step 3: Check what getAllPhoneFormats generates
  console.log('\n=== PHONE FORMATS GENERATED BY getAllPhoneFormats ===');
  
  function getAllPhoneFormats(phone: string): string[] {
    if (!phone) return [];
    
    const cleaned = phone.replace(/\D/g, '');
    const last10 = cleaned.slice(-10);
    
    if (last10.length !== 10) return [phone];
    
    const formats = [
      `+1${last10}`,                                                                // E.164: +19016796871
      last10,                                                                        // 10 digits: 9016796871
      `1${last10}`,                                                                  // 11 digits: 19016796871
      `(${last10.slice(0, 3)}) ${last10.slice(3, 6)}-${last10.slice(6)}`,          // Formatted: (901) 679-6871
    ];
    
    return [...new Set(formats)];
  }
  
  const formats = getAllPhoneFormats(normalizedPhone);
  console.log('Formats that will be searched:');
  formats.forEach(f => console.log(`  - "${f}"`));
  
  // Direct database check
  console.log('\n=== DIRECT DATABASE CHECK ===');
  const admin = await import('firebase-admin');
  
  if (!admin.apps.length) {
    admin.initializeApp({
      credential: admin.credential.cert({
        projectId: process.env.FIREBASE_PROJECT_ID!,
        privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
        clientEmail: process.env.FIREBASE_CLIENT_EMAIL!,
      })
    });
  }
  
  const db = admin.firestore();
  
  for (const format of formats) {
    const snapshot = await db.collection('users')
      .where('phone', '==', format)
      .limit(1)
      .get();
    
    if (!snapshot.empty) {
      console.log(`✅ Found in DB with format: "${format}"`);
      const user = snapshot.docs[0].data();
      console.log(`   Stored phone: "${user.phone}"`);
      break;
    } else {
      console.log(`❌ Not found with format: "${format}"`);
    }
  }
}

debugJuanLogin().then(() => {
  console.log('\n✅ Debug complete!');
  process.exit(0);
}).catch(err => {
  console.error('Error:', err);
  process.exit(1);
});